### ISSUE TITLE
Add new APIs for manager view functions

### ISSUE THREAD

**Issue by jmbockhorst** [jerometujague/SoftwareEngineeringProject#115]
We will need to add new APIs for the manager view functions.

- Add or update branch hours: `/api/branchHours`
- Add, edit, or remove manager unavailabilities: `/api/unavailables/manager`
- Add, edit, or remove branch unavailabilities: `/api/unavailables/branch`
- Add, edit, or remove managers: `/api/managers`
- Add, edit, or delete services: `/api/services`
- Add, edit, or delete branches: `/api/branches`

**Comment by jmbockhorst** [comment]
@dbruce Here is how you can test the http requests from the command line:

`curl -H "Accept: application/json" -H "Content-Type: application/json" -X POST --data [1, 3] localhost:8080/api/branches`

Or for complex data objects, it is easiest to put the JSON data in a separate file:

`curl -H "Accept: application/json" -H "Content-Type: application/json" -X POST --data @data.json localhost:8080/api/appointments/add`

**data.json**
```
{
    "calendarId": "1",
    "time": "10:00",
    "branchId": "1",
    "customerId": "1",
    "serviceIds": [
        "1",
        "2"
    ],
    "note": "Customer note",
    "emailConsent": "false"
}
```

**Comment by dbruce** [comment]
Thanks, that will help!

**Comment by dbruce** [comment]
Changes to managers, branch hours, services, and branches are all working. Also, deleting from the branch_unavailable or manager_unavailable tables works. I get database errors when I try to add something to the unavailable table. Something about a foreign key to the calendar table.

**Comment by jmbockhorst** [comment]
Is the calendar_id that you are inserting a valid calendar_id in the calendar table? That would be the only thing I can think of.

**Comment by jmbockhorst** [comment]
I saw this line of code in the UnavailableDAO:
`Unavailable unavailable1 = unavailables.get(unavailables.size());`

Wouldn't that give you an out of bounds error?

**Comment by dbruce** [comment]
You're right about the out-of-bounds error (forgot to subtract one), but the database error occurs before that even with everything after commented out. I'm going to try some other things today and Jerome said he will look at it tomorrow with me.

**Comment by jmbockhorst** [comment]
This line is wrong:
`INSERT INTO manager_unavailable (calendar_id, manager_id) VALUES (?, ?)`
'calendar_id' should be 'unavailable_id'

**Comment by jmbockhorst** [comment]
It worked for me after those fixes. We also need to check if the unavailable with that calendar_id and time is already in the database, so we don't create duplicates.

**Comment by dbruce** [comment]
I had made a mistake in my data.json file.  Amazing how working when you're not tired is so much better... Everything works fine now.
