### ISSUE TITLE
Manager view UI design

### ISSUE THREAD

**Issue by jmbockhorst** [jerometujague/SoftwareEngineeringProject#118]
We need to talk about the UI design of the manager view page. Since we don't have a guide to follow, there are a few different ways we can implement this. 

So the first question is the overall general design. We could do either a vertical or horizontal design.

## Vertical

![IMG_4578](https://user-images.githubusercontent.com/44308390/55033151-7a9eb200-4fe0-11e9-886e-b8425297a747.jpg)

## Horizontal

![IMG_4577](https://user-images.githubusercontent.com/44308390/55033157-7d010c00-4fe0-11e9-9a76-c6d0c42444b5.jpg)

Also, should we hide the previous list of options when we move to the next?

Then we will have each view for each of the editable options. Here are a some initial sketches that I made:

## View appointments

![IMG_4574](https://user-images.githubusercontent.com/44308390/55033038-3ad7ca80-4fe0-11e9-9c05-047f89ab3f5c.jpg)

## Branch hours

![IMG_4575](https://user-images.githubusercontent.com/44308390/55033093-58a52f80-4fe0-11e9-88d2-ac1f274edae3.jpg)

## Managers

![IMG_4576](https://user-images.githubusercontent.com/44308390/55033136-74103a80-4fe0-11e9-9cf7-fe7a5b44358a.jpg)

And finally, we will need to figure out how we want to organize all of the information. 

For example, right now I just have three main categories: Branches, Appointments, and Managers. This way unavailabilities would be added through the branches or managers tabs. But we could make a separate category for adding unavailables, and specify manager or branch through there. There are a few other things that could be done in different ways like this, so we will need to figure that out.

@jerometujague @dbruce @KRG74790 @nikfusco @christinevfalk @oliviaerickson @tlc93290 
Let me know your thoughts about this. And if you want to make some prototypes with your own ideas, that would be great and please do. Thanks!

UPDATE:
The branch/branches will be chosen first. A button will bring up a popup that lets the selected branches be changed at any time. 

Here are the main categories that will always stay visible in a vertical sidebar:

- Appointments
- Managers
- Manager Scheduling
- Branch Scheduling 
- Branch hours

**Comment by jerometujague** [comment]
I like the horizontal view. It looks clean. It might not be a bad idea to have unavailables in their own separate category, just to keep the views of the other three categories more simplistic.
