### ISSUE TITLE
Send email when appointment is cancelled or edited

### ISSUE THREAD

**Issue by jmbockhorst** [jerometujague/SoftwareEngineeringProject#125]
I think we want to send an email to both the customer and manager when an appointment is cancelled or edited.

**Comment by dbruce** [comment]
Still in progress. My wifi dropped in the middle of the initial push, so my computer thought it pushed the changes, but they were not in GitHub. I had to make other (minor) changes to commit and push the files again. I've only moved original email capability to another class (MailContent) for now, to clean up the AppointmentController class.  I'll finish methods for sending emails for changed & cancelled appointments probably tomorrow.

**Comment by dbruce** [comment]
Mostly done. Not sure how to edit an appointment on the front end, so I'm not sure how to word the email.

**Comment by jmbockhorst** [comment]
Probably just something simple like "Your appointment has been updated, here are the new details..."

FYI, you can create a [draft pull request](https://i1.wp.com/user-images.githubusercontent.com/3477155/52671177-5d0e0100-2ee8-11e9-8645-bdd923b7d93b.gif?resize=1024%2C512&ssl=1) if you want to start discussion on some code, but it isn't ready to merge yet.
