### ISSUE TITLE
Style the edit dialog

### ISSUE THREAD

**Issue by jmbockhorst** [jerometujague/SoftwareEngineeringProject#143]
The edit dialog on the manager view needs to be styled better. We need a better way to show the edit dialog on one line and make it work for a variable amount of edit fields.

**Comment by nikfusco** [comment]
Working on this this afternoon, as well as making the manager view responsive for mobile.

**Comment by jmbockhorst** [comment]
@nikfusco Hopefully you saw the branches that Kyle and I have done some work on. Also, I would focus on the customer view being responsive for mobile before the manager view, since that's what was asked. https://commercebank.azurewebsites.net is live with the latest from the `mobile` branch, if you want to test it and see what else needs work.

**Comment by nikfusco** [comment]
@jmbockhorst I did see the customer view was being worked on, and I suppose I assumed it was still being worked on so I grabbed something else. That's my mistake. If there's more work left for that I can certainly help there as well.

**Comment by jmbockhorst** [comment]
Yeah, no worries. If you want to, you can continue from what I was doing on the customer view. I just started doing a little bit but not much. See #157.
