### ISSUE TITLE
Display email sender as a name

### ISSUE THREAD

**Issue by jmbockhorst** [jerometujague/SoftwareEngineeringProject#58]
We should use the InternetAddress object as the input for the mail sender. That way it shows a name instead of email address. For the name we could use something like "Commerce Bank".
`helper.setFrom(new InternetAddress("seclassproject@gmail.com", "Commerce Bank"));`

**Comment by dbruce** [comment]
Done, although slightly different from your suggestion. I'll push with other issue commits later. I'm using "UCM SE3910 Project" as the name. Just in case an email gets inadvertently sent to the wrong place, I don't want it to appear as if Commerce Bank sent it.

**Comment by jmbockhorst** [comment]
Yes, that's smart.
