### ISSUE TITLE
Style customer view page

### ISSUE THREAD

**Issue by jmbockhorst** [jerometujague/SoftwareEngineeringProject#66]
Style the customer view to somewhat match the example. 

- [x] Specifically, the customer info page needs to be laid out better.
- [x] The date picker could use some styling
- [x] Email consent checkbox

**Comment by KRG74790** [comment]
Is this done or what needs to be done on it?

**Comment by jmbockhorst** [comment]
Some things still need to be done. Like the customer info page and optimizing for mobile.

**Comment by tlc93290** [comment]
I will be taking a look at it this weekend styling wise. I will see if I can get it set up for mobile, if not I may need some help with that.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by KRG74790** [comment]
This should be completed!
